version: '3.8'

services:
  anvil:
    image: ghcr.io/foundry-rs/foundry:latest
    entrypoint: anvil
    command: --host 0.0.0.0 --port 8545
    ports:
      - "8545:8545"
    networks:
      - blockchain-network

  backend:
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
    depends_on:
      - anvil
    networks:
      - blockchain-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:3001
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    stdin_open: true
    tty: true
    networks:
      - blockchain-network

networks:
  blockchain-network:
    driver: bridge